server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djoh88/spring_cloud_config
          #          uri: file:///Users/hi080/Desktop/git-local-repo
          #private
#          password:
#          username:
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
